name: "Data Connector Jobs"
jobs:
  - name: "Binance Prices Daily"
    resource:
      notebook:
        path: "notebooks/binance_daily.ipynb"
    schedule:
      type: "crontab"
      expression: "0 0 * * *"

  - name: "Alpacaa Prices Daily Test"
    resource:
      notebook:
        path: "notebooks/alpaca_daily_test.ipynb"
    schedule:
      type: "crontab"
      expression: "0 0 * * *"

  - name: "Alpaca Prices Daily"
    resource:
      notebook:
        path: "notebooks/alpaca_daily.ipynb"
    schedule:
      type: "crontab"
      expression: "0 0 * * *"

  - name: "Fundamentals"
    resource:
      notebook:
        path: "notebooks/fundamentals.ipynb"
    schedule:
      type: "crontab"
      expression: "0 0 * * *"

  - name: "Coingecko Market Cap"
    resource:
      notebook:
        path: "notebooks/coingecko_market_cap.ipynb"
    schedule:
      type: "crontab"
      expression: "0 0 * * *"

  - name: "Polygon Market Cap"
    resource:
      notebook:
        path: "notebooks/polygon_market_cap.ipynb"
    schedule:
      type: "crontab"
      expression: "0 0 * * *"

#  - name: "Asset Translation Tables"
#    resource:
#      notebook:
#        path: "data_connectors/scripts/create_translation_tables.py"


  - name: "Banxico MBONOS"
    resource:
      notebook:
        path: "notebooks/banxico_mbonos.ipynb"
    schedule:
      type: "crontab"
      expression: "0 0 * * *"

  - name: "Banxico TIEE Fixing"
    resource:
      notebook:
        path: "notebooks/banxico_tiie_fixing.ipynb"
    schedule:
      type: "crontab"
      expression: "0 0 * * *"

  - name: "Discount Curves"
    resource:
      notebook:
        path: "notebooks/discount_curves.ipynb"
    schedule:
      type: "crontab"
      expression: "0 0 * * *"

  - name: "Valmer Vector Update"
    resource:
      notebook:
        path: "notebooks/valmer_prices.ipynb"
    schedule:
      type: "crontab"
      expression: "0 0 * * *"